### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by Dark32** [Dark32/vkNotification#10]
```
9
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto                                                                                                                         
    return self._sock.recv_into(b)                                                                                                                                                   
  File "/usr/lib/python3.4/ssl.py", line 745, in recv_into                                                                                                                           
    return self.read(nbytes, buffer)                                                                                                                                                 
  File "/usr/lib/python3.4/ssl.py", line 617, in read                                                                                                                                
    v = self._sslobj.read(len, buffer)                                                                                                                                               
ConnectionResetError: [Errno 104] Connection reset by peer                                                                                                                           

During handling of the above exception, another exception occurred:                                                                                                                  

Traceback (most recent call last):                                                                                                                                                   
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 376, in send                                                                                              
    timeout=timeout                                                                                                                                                                  
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 609, in urlopen                                                                    
    _stacktrace=sys.exc_info()[2])                                                                                                                                                   
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/util/retry.py", line 247, in increment                                                                      
    raise six.reraise(type(error), error, _stacktrace)                                                                                                                               
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/packages/six.py", line 309, in reraise                                                                      
    raise value.with_traceback(tb)                                                                                                                                                   
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen                                                                    
    body=body, headers=headers)                                                                                                                                                      
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/connectionpool.py", line 378, in _make_request                                                              
    httplib_response = conn.getresponse()                                                                                                                                            
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse                                                                                                                
    response.begin()                                                                                                                                                                 
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 745, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 617, in read
    v = self._sslobj.read(len, buffer)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vkNoty.py", line 6, in <module>
    main.enable().main_loop()
  File "/home/andrew/nord/vkNotification/main.py", line 78, in main_loop
    self.loop()  # то запускаем петлю
  File "/home/andrew/nord/vkNotification/main.py", line 101, in loop
    messages, self.pts = self.__get_long_poll_history()  # получаем лс
  File "/home/andrew/nord/vkNotification/main.py", line 155, in __get_long_poll_history
    data = self.vk.method('messages.getLongPollHistory', {'ts': self.ts, 'pts': self.pts, 'fields': fields})
  File "/home/andrew/nord/vkNotification/vk_api/vk_api.py", line 392, in method
    response = self.http.post(url, values)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by Dark32** [comment]
```
('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "vkNoty.py", line 8, in <module>
    main.enable().main_loop()
  File "/home/andrew/nord/vkNotification/main.py", line 81, in main_loop
    self.loop()  # то запускаем петлю
  File "/home/andrew/nord/vkNotification/main.py", line 104, in loop
    messages, self.pts = self.__get_long_poll_history()  # получаем лс
TypeError: 'NoneType' object is not iterable
```
