### ISSUE TITLE
Краш KeyError: 'ts'

### ISSUE THREAD

**Issue by Dark32** [Dark32/vkNotification#3]
```
Traceback (most recent call last):
  File "main.py", line 212, in <module>
    main()
  File "main.py", line 70, in main
    ts = data['ts']
KeyError: 'ts'
```

**Comment by Dark32** [comment]
https://github.com/Dark32/vkNotification/blob/master/main.py#L71 проверка после выполнения операции
https://github.com/Dark32/vkNotification/blob/master/main.py#L70 фейл не всегда даёт ts
